name: Tests 
on: push


jobs:
  hadolint:
    runs-on: ubuntu-latest
    name: Check docker images (Hadolint)
    container: hadolint/hadolint
    steps:
      - name: checking source code
        uses: actions/checkout@v2
      - name: hadolint testing code
        run: hadolint Dockerfile

  deploy:
    name: Run unit test (PHPUnit)
    runs-on: unbuntu-latest
    container: djemal/blog_php
    needs:
      - hadolint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Install dependencies (composer)
        run: composer install
      - name: run unit tests 
        run: php bin/phpunit
 
